################################################################################
# \file tfm_ns.mk
# \version 1.0
#
# \brief
# Trusted Firmware-M (TF-M) non-secure image make file
#
################################################################################
# \copyright
# (c) 2022-2026, Infineon Technologies AG, or an affiliate of Infineon
# Technologies AG. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

# Makefile with common macros
include $(join $(dir $(lastword $(MAKEFILE_LIST))),common.mk)


################################################################################
# Extract data from TF-M secure build
################################################################################

# Extract targets which triggers build
IS_BUILD_TARGET=$(findstring all,$(MAKECMDGOALS))$(findstring build_proj,$(MAKECMDGOALS))

# Validate presence of $(TFM_INSTALL_PATH) - path to non-secure interface installed by TF-M secure build
ifneq ($(IS_BUILD_TARGET),)
ifeq ($(wildcard $(TFM_INSTALL_PATH)),)
$(error "\"$(TFM_INSTALL_PATH)\" is not found, please validate path and/or build TF-M secure application")
endif
endif


################################################################################
# TF-M non-secure interface
################################################################################

###################################### SRF #####################################

ifneq ($(wildcard $(TFM_INSTALL_PATH)/interface/src/ifx_mtb_srf.c),)
DEFINES+=MTB_SRF_USE_PSA
DEFINES+=MTB_SRF_CUSTOM_REQUEST_SUBMIT
DEFINES+=IFX_MTB_SRF
endif # SRF configuration

################################## MTB Mailbox #################################

# Detect MTB Mailbox source location (new or legacy path)
IFX_MTB_MAILBOX_SRC_DIR:=$(firstword $(wildcard \
    $(TFM_INSTALL_PATH)/interface/src/ifx_mtb_mailbox \
    $(TFM_INSTALL_PATH)/interface/src/multi_core))
IFX_MTB_MAILBOX_SRC:=$(wildcard $(IFX_MTB_MAILBOX_SRC_DIR)/ifx_mtb_mailbox.c)

ifneq ($(IFX_MTB_MAILBOX_SRC),)
# For IFX_MTB_MAILBOX - on core NSPE acts like a proxy for off core
# NSPE requests. Thus ifx_mtb_mailbox include directory is added to both - on
# core and off core NSPEs include directories so that they can work with MTB
# mailbox request types.
# New layout (2.3.x): interface/include/ifx_mtb_mailbox
# Legacy layout (2.1.x): interface/include/multi_core
IFX_MTB_MAILBOX_INC_DIR:=$(firstword $(wildcard \
    $(TFM_INSTALL_PATH)/interface/include/ifx_mtb_mailbox \
    $(TFM_INSTALL_PATH)/interface/include/multi_core))
INCLUDES+=$(IFX_MTB_MAILBOX_INC_DIR)

DEFINES+=IFX_MTB_MAILBOX=1
# Enable address remap if MTB mailbox is built, to support CM55 TCM memory
DEFINES+=CONFIG_TFM_PSA_CALL_ADDRESS_REMAP=1

# Enable MTB mailbox and SRF relay from TFM
DEFINES+=MTB_SRF_CUSTOM_IPC_REQUEST_SUBMIT # TFM uses own SRF IPC request handling mechanism
DEFINES+=MTB_SRF_CUSTOM_PROCESS_REQUEST # TFM uses own SRF process request handling mechanism
DEFINES+=MTB_SRF_IPC_CUSTOM_PACKET_TYPE # TFM uses own SRF IPC packet type to implement PSA call functionality
endif # MTB Mailbox configuration

############################ Communication interface ###########################

ifeq ($(IFX_NS_INTERFACE_TZ),1) # TZ interface
DEFINES+=IFX_NS_INTERFACE_TZ=1

# Use veneer generated by TF-M secure build
NSC_VENEER=$(wildcard ../install/interface/lib/*.o)

ifeq ($(filter $(COMPONENTS),RTOS_AWARE),)
# Bare-metal configuration
TFM_SOURCES+=$(wildcard $(TFM_INSTALL_PATH)/interface/src/os_wrapper/tfm_ns_interface_bare_metal.c)
else # RTOS configuration
# RTOS configuration
DEFINES+=COMPONENT_RTOS_AWARE
TFM_SOURCES+=$(wildcard $(TFM_INSTALL_PATH)/interface/src/os_wrapper/os_wrapper_cyabs_rtos.c)
TFM_SOURCES+=$(wildcard $(TFM_INSTALL_PATH)/interface/src/os_wrapper/tfm_ns_interface_rtos.c)
endif # RTOS configuration

# When MTB Mailbox is enabled, on-core NSPE acts as a proxy for off-core NSPE requests.
# Include proxy-related sources only in this configuration.
ifneq ($(IFX_MTB_MAILBOX_SRC),)
# Include CM55 multi-core HAL and region utilities only when the secure-side
# install provides the platform-specific HAL source. This keeps address remap
# support enabled only for platforms/configurations that require it.
ifneq ($(wildcard $(IFX_MTB_MAILBOX_SRC_DIR)/platform_hal_multi_core_cm55.c),)
TFM_SOURCES+=$(wildcard $(IFX_MTB_MAILBOX_SRC_DIR)/platform_hal_multi_core_cm55.c)
TFM_SOURCES+=$(wildcard $(TFM_INSTALL_PATH)/platform/ifx/utils/ifx_regions.c)
endif # MTB Mailbox multi-core HAL
endif # MTB Mailbox

else ifeq ($(IFX_NS_INTERFACE_MAILBOX),1) # Mailbox interface
DEFINES+=IFX_NS_INTERFACE_MAILBOX=1

# Ignore TZ interface
TFM_IGNORE_SOURCES+=$(wildcard $(TFM_INSTALL_PATH)/interface/src/tfm_tz_psa_ns_api.c)

ifneq ($(IFX_MTB_MAILBOX_SRC),) # MTB Mailbox interface
# IFX MTB Mailbox interface
# New layout (2.3.x): ifx_mtb_mailbox_psa_ns_api.c
# Legacy layout (2.1.x): tfm_multi_core_psa_ns_api.c
IFX_MTB_MAILBOX_PSA_NS_API:=$(firstword $(wildcard \
    $(IFX_MTB_MAILBOX_SRC_DIR)/ifx_mtb_mailbox_psa_ns_api.c \
    $(IFX_MTB_MAILBOX_SRC_DIR)/tfm_multi_core_psa_ns_api.c))
TFM_SOURCES+=$(IFX_MTB_MAILBOX_PSA_NS_API)
TFM_SOURCES+=$(IFX_MTB_MAILBOX_SRC)

else ifneq ($(wildcard $(TFM_INSTALL_PATH)/interface/src/multi_core/tfm_multi_core_psa_ns_api.c),) # TF-M mailbox (TFM_PARTITION_NS_AGENT_MAILBOX)
ifeq ($(filter $(COMPONENTS),RTOS_AWARE),RTOS_AWARE)
# Enable RTOS support for mailbox
DEFINES+=TFM_MULTI_CORE_NS_OS TFM_MULTI_CORE_TOPOLOGY
endif

ifeq ($(filter $(DEFINES),TFM_MULTI_CORE_NS_OS_MAILBOX_THREAD),)
TFM_SOURCES+=$(wildcard $(TFM_INSTALL_PATH)/interface/src/multi_core/tfm_ns_mailbox.c)
else ifneq ($(filter $(DEFINES),TFM_MULTI_CORE_NS_OS),)
TFM_SOURCES+=$(wildcard $(TFM_INSTALL_PATH)/interface/src/multi_core/tfm_ns_mailbox_thread.c)
endif # Mailbox thread

ifneq ($(filter $(DEFINES),TFM_MULTI_CORE_NS_OS),)
TFM_SOURCES+=$(wildcard $(TFM_INSTALL_PATH)/interface/src/os_wrapper/os_wrapper_cyabs_rtos.c)
TFM_SOURCES+=$(wildcard $(TFM_INSTALL_PATH)/interface/src/multi_core/tfm_ns_mailbox_rtos_api.c)
endif # Mailbox multi-core OS support

INCLUDES+=$(wildcard $(TFM_INSTALL_PATH)/interface/include/multi_core)
TFM_SOURCES+=$(wildcard $(TFM_INSTALL_PATH)/interface/src/multi_core/platform_multicore.c)
TFM_SOURCES+=$(wildcard $(TFM_INSTALL_PATH)/interface/src/multi_core/platform_ns_mailbox.c)
TFM_SOURCES+=$(wildcard $(TFM_INSTALL_PATH)/interface/src/multi_core/tfm_multi_core_ns_api.c)
TFM_SOURCES+=$(wildcard $(TFM_INSTALL_PATH)/interface/src/multi_core/tfm_multi_core_psa_ns_api.c)
endif # Mailbox type

else # Communication interface
$(error Either IFX_NS_INTERFACE_TZ or IFX_NS_INTERFACE_MAILBOX must be defined)
endif # Communication interface

############################## Include directories #############################

INCLUDES+=$(wildcard $(TFM_INSTALL_PATH)/interface/include)
INCLUDES+=$(wildcard $(TFM_INSTALL_PATH)/interface/include/mbedtls)
INCLUDES+=$(wildcard $(TFM_INSTALL_PATH)/platform/board)
INCLUDES+=$(wildcard $(TFM_INSTALL_PATH)/platform/board/shared)
INCLUDES+=$(wildcard $(TFM_INSTALL_PATH)/platform/board/shared/device/include)
INCLUDES+=$(wildcard $(TFM_INSTALL_PATH)/platform/device/include)
INCLUDES+=$(wildcard $(TFM_INSTALL_PATH)/platform/ext/common)
INCLUDES+=$(wildcard $(TFM_INSTALL_PATH)/platform/family/shared)
INCLUDES+=$(wildcard $(TFM_INSTALL_PATH)/platform/family/shared/device/include)
INCLUDES+=$(wildcard $(TFM_INSTALL_PATH)/platform/family/shared/partition)
# Legacy layout (2.1.x): the family folder is named after the platform family
# (e.g. pse84, psc3) instead of the generic "family". Add wildcard fallbacks so
# platform headers such as tfm_peripherals_def.h are found. Duplicate include
# paths (board/ifx) are harmless.
INCLUDES+=$(wildcard $(TFM_INSTALL_PATH)/platform/*/shared)
INCLUDES+=$(wildcard $(TFM_INSTALL_PATH)/platform/*/shared/device/include)
INCLUDES+=$(wildcard $(TFM_INSTALL_PATH)/platform/*/shared/device/config)
INCLUDES+=$(wildcard $(TFM_INSTALL_PATH)/platform/*/shared/partition)
INCLUDES+=$(wildcard $(TFM_INSTALL_PATH)/platform/ifx/device/include)
INCLUDES+=$(wildcard $(TFM_INSTALL_PATH)/platform/ifx/shared)
INCLUDES+=$(wildcard $(TFM_INSTALL_PATH)/platform/ifx/utils)
INCLUDES+=$(wildcard $(TFM_INSTALL_PATH)/platform/include)
INCLUDES+=$(wildcard $(TFM_INSTALL_PATH)/platform/shared)
INCLUDES+=$(wildcard $(TFM_INSTALL_PATH)/platform/shared/device/include)
INCLUDES+=$(wildcard $(TFM_INSTALL_PATH)/platform/shared/partition)

############################## Compile definitions #############################

DEFINES+=DOMAIN_NS=1
DEFINES+=TFM_PSA_CRYPTO_CLIENT_ONLY

# Core identifiers used across all Infineon platforms
DEFINES+=IFX_CM33=33
DEFINES+=IFX_CM55=55

# Derive IFX_CORE from the core selected by the MTB build
ifeq ($(filter CM33 CM55,$(CORE)),)
$(error Unsupported CORE=$(CORE). Supported cores are CM33 and CM55)
endif
DEFINES+=IFX_CORE=IFX_$(CORE)

################## Required config files definitions for TF-M ##################

ifneq ($(wildcard $(TFM_INSTALL_PATH)/interface/include/tfm_psa_crypto_config_client.h),)
ifeq ($(filter MBEDTLS_PSA_CRYPTO_CONFIG_FILE=%,$(DEFINES)),)
DEFINES+=MBEDTLS_PSA_CRYPTO_CONFIG_FILE=\"tfm_psa_crypto_config_client.h\"
endif # MBEDTLS_PSA_CRYPTO_CONFIG_FILE
endif # tfm_psa_crypto_config_client.h

ifneq ($(wildcard $(TFM_INSTALL_PATH)/interface/include/tfm_mbedcrypto_config_client.h),)
ifeq ($(filter MBEDTLS_CONFIG_FILE=%,$(DEFINES)),)
DEFINES+=MBEDTLS_CONFIG_FILE=\"tfm_mbedcrypto_config_client.h\"
endif # MBEDTLS_CONFIG_FILE
endif # tfm_mbedcrypto_config_client.h

# Unconditional definitions to ensure required config files are used
ifeq ($(filter TF_PSA_CRYPTO_CONFIG_FILE=%,$(DEFINES)),)
DEFINES+=TF_PSA_CRYPTO_CONFIG_FILE=\"tf_psa_crypto_config.h\"
endif # TF_PSA_CRYPTO_CONFIG_FILE

##################### Conditional config files definitions #####################

ifeq ($(filter TARGET_CONFIG_HEADER_FILE=%,$(DEFINES)),)
ifneq ($(wildcard $(TFM_INSTALL_PATH)/interface/include/config_tfm_target.h),)
DEFINES+=TARGET_CONFIG_HEADER_FILE=\"config_tfm_target.h\"
endif
endif # TARGET_CONFIG_HEADER_FILE

ifeq ($(filter CRYPTO_HW_ACCELERATOR_CONFIG=%,$(DEFINES)),)
ifneq ($(wildcard $(TFM_INSTALL_PATH)/interface/include/crypto_hw_accelerator_config.h),)
DEFINES+=CRYPTO_HW_ACCELERATOR_CONFIG=\"crypto_hw_accelerator_config.h\"
endif
endif # CRYPTO_HW_ACCELERATOR_CONFIG

ifeq ($(filter IFX_PROJECT_CONFIG_PATH=%,$(DEFINES)),)
ifneq ($(wildcard $(TFM_INSTALL_PATH)/interface/include/ifx_project_config.h),)
DEFINES+=IFX_PROJECT_CONFIG_PATH=\"ifx_project_config.h\"
endif
endif # IFX_PROJECT_CONFIG_PATH

ifeq ($(filter PROJECT_CONFIG_HEADER_FILE=%,$(DEFINES)),)
ifneq ($(wildcard $(TFM_INSTALL_PATH)/interface/include/config_tfm_project.h),)
DEFINES+=PROJECT_CONFIG_HEADER_FILE=\"config_tfm_project.h\"
endif
endif # PROJECT_CONFIG_HEADER_FILE

ifeq ($(filter MBEDTLS_PSA_CRYPTO_PLATFORM_FILE=%,$(DEFINES)),)
# Check both possible locations: mbedtls subfolder (2.3.x) and interface/include root (2.1.x)
ifneq ($(wildcard $(TFM_INSTALL_PATH)/interface/include/mbedtls/tfm_mbedtls_psa_crypto_platform.h),)
DEFINES+=MBEDTLS_PSA_CRYPTO_PLATFORM_FILE=\"tfm_mbedtls_psa_crypto_platform.h\"
else ifneq ($(wildcard $(TFM_INSTALL_PATH)/interface/include/tfm_mbedtls_psa_crypto_platform.h),)
DEFINES+=MBEDTLS_PSA_CRYPTO_PLATFORM_FILE=\"tfm_mbedtls_psa_crypto_platform.h\"
endif
endif # MBEDTLS_PSA_CRYPTO_PLATFORM_FILE

############################### Interface sources ##############################

# Compile TF-M non-secure interface
TFM_SOURCES+=$(wildcard $(TFM_INSTALL_PATH)/interface/src/*.c)
# Filter out sources
SOURCES+=$(filter-out $(TFM_IGNORE_SOURCES),$(TFM_SOURCES))
